from pathlib import Path

BROKER_HOST = "127.0.0.1"
BROKER_PORT = 5051
DEFAULT_SUBSCRIBER_HOST = "127.0.0.1"

RPC_TIMEOUT = 5.0
BROKER_RPC_WORKERS = 12
SUBSCRIBER_RPC_WORKERS = 8
DELIVERY_WORKERS = 4
MAX_DELIVERY_ATTEMPTS = 3
RETRY_SCAN_INTERVAL = 1.0
RETRY_BASE_DELAY = 2

DATABASE_PATH = Path(__file__).resolve().parent / "database" / "broker_grpc.db"
