from pathlib import Path

BROKER_HOST = "127.0.0.1"
BROKER_PORT = 5000
DEFAULT_SUBSCRIBER_HOST = "127.0.0.1"

SOCKET_TIMEOUT = 5.0
MAX_MESSAGE_SIZE = 1024 * 1024
HEADER_SIZE = 4

BROKER_CLIENT_WORKERS = 12
DELIVERY_WORKERS = 4
SUBSCRIBER_WORKERS = 8
MAX_DELIVERY_ATTEMPTS = 3
RETRY_SCAN_INTERVAL = 1.0
RETRY_BASE_DELAY = 2

DATABASE_DIR = Path(__file__).resolve().parent / "database"
DATABASE_PATH = DATABASE_DIR / "broker.db"
